import { createContext, useContext, useEffect, useMemo, useState } from 'react';
import API from '../api';

const LanguageContext = createContext();

const translations = {
  en: {
    home: 'Home',
    questions: 'Questions',
    community: 'Community',
    tags: 'Tags',
    users: 'Users',
    jobs: 'Jobs',
    admin: 'Admin',
    myProfile: 'My Profile',
    logout: 'Logout',
    logIn: 'Log In',
    signUp: 'Sign Up',
    searchQuestions: 'Search questions...',
    askQuestion: 'Ask Question',
    allQuestions: 'All Questions',
    questionsCount: '{count} Questions',
    newest: 'Newest',
    active: 'Active',
    unanswered: 'Unanswered',
    all: 'All',
    noQuestionsFound: 'No Questions Found',
    loadingQuestions: 'Loading Questions...',
    votes: 'Votes',
    answers: 'Answers',
    views: 'Views',
    navigation: 'Navigation',
    loginTitle: 'Log In',
    signupTitle: 'Sign Up',
    email: 'Email',
    password: 'Password',
    name: 'Name',
    forgotPassword: 'Forgot Password?',
    oneTimePassword: 'One-Time Password',
    enterCode: 'Enter 6-digit code',
    verifyOtp: 'Verify OTP',
    saveProfile: 'Save Profile',
    cancel: 'Cancel',
    editProfile: 'Edit Profile',
    about: 'About',
    skills: 'Skills',
    language: 'Language',
    selectLanguage: 'Select Language',
    currentPlan: 'Current plan:',
    questionsPerDay: 'questions/day',
    questionTitle: 'Question title',
    questionTitlePlaceholder: 'Enter a clear, specific title',
    questionDescription: 'Question description',
    questionDescriptionPlaceholder: 'Describe your question in detail',
    questionTagsPlaceholder: 'Add tags separated by commas',
    questionTagsExample: 'Example: react, node.js, mongodb',
    submitting: 'Submitting...',
    updateQuestion: 'Update Question',
    verifyEmail: 'Verify Email',
    otpPrompt: 'Enter the OTP sent to your {channel} to continue.',
    latest: 'Latest',
    following: 'Following',
    saved: 'Saved',
    search: 'Search',
    trendingNow: 'Trending now',
    shareUpdate: 'Share an update',
    image: 'Image',
    publish: 'Publish',
    noPostsFound: 'No posts found',
    communityDescription: 'Projects, code, learning wins, and helpful technical conversations.',
    searchHashtag: 'Search or #hashtag',
    likes: 'likes',
    comments: 'comments',
    postPlaceholder: 'Share a project, achievement, or question. Use #hashtags and @mentions.',
    codeSnippetPlaceholder: 'Optional code snippet',
    deletePostConfirmation: 'Delete this post?',
    editPostPrompt: 'Edit your post',
    loadingMorePosts: 'Loading more posts…',
    scrollToLoadMorePosts: 'Scroll to load more posts…',
    tryAnotherSearch: 'Try another search or be the first to share.',
    reply: 'Reply',
    comment: 'Comment',
    writeReply: 'Write a reply…',
    writeComment: 'Write a comment…',
    loadingJobs: 'Loading jobs...',
    jobsAvailable: 'Jobs Available',
    noJobsPosted: 'No jobs posted yet.',
    postJob: 'Post a Job',
    jobTitle: 'Job Title',
    company: 'Company',
    location: 'Location',
    salary: 'Salary',
    requirements: 'Requirements',
    followers: 'Followers',
    activeSessions: 'Active Sessions',
    trustDevice: 'Trust device',
    revokeSession: 'Revoke session',
    reputationHistory: 'Reputation History',
    transferReputation: 'Transfer Reputation',
    joinedOn: 'Joined on',
    subscriptionBilling: 'Subscription & Billing Dashboard',
    activePlan: 'Active Plan',
    renewalDate: 'Renewal Date',
    questionLimit: 'Question Limit',
    unlimited: 'Unlimited',
    upgradeMembership: 'Upgrade Membership',
    upgradeTo: 'Upgrade to',
    paymentHistory: 'Payment History & Invoices',
    amount: 'Amount',
    invoice: 'Invoice',
    downloadInvoice: 'Download invoice',
    pending: 'Pending',
    overflowBlog: 'The Overflow Blog',
    welcomeToNexStack: 'Welcome to NexStack',
    tipsForQuestions: 'Tips for asking better programming questions',
    learnMern: 'Learn MERN Stack through real projects',
    featuredOnMeta: 'Featured on Meta',
    askClearQuestions: 'Ask clear and detailed questions.',
    helpOtherDevelopers: 'Help other developers by answering.',
    voteUseful: 'Vote for useful questions and answers.',
    hotTags: 'Hot Tags',
    communityStats: 'Community Stats',
    switchLanguage: 'Switch Language',
    languageUpdated: 'Language updated successfully.',
    "Live Count": "Live Count",
    "Registered Members": "Registered Members",
    "Find answers and share your technical questions": "Find answers and share your technical questions",
    "Browse real developer questions, join discussions, and post your own programming issues.": "Browse real developer questions, join discussions, and post your own programming issues.",
    postAnswer: 'Post Answer',
    backToQuestions: 'Back to Questions',
    edit: 'Edit',
    delete: 'Delete',
    acceptedAnswer: 'Accepted Answer',
    bestAnswer: 'Best Answer',
    acceptAnswer: 'Accept Answer',
    reputation: 'Reputation',
    totalUsers: 'Total users',
    totalPosts: 'Total posts',
    totalReports: 'Open reports',
    activeUsers: 'Active users (30 days)',
    suspendedUsers: 'Suspended users',
    couldNotLoadModeration: 'Could not load the moderation dashboard.',
    suspensionReason: 'Suspension reason',
    reportsAgainst: 'Reports against this account',
    communityGuidelineViolation: 'Community guideline violation',
    loadingDashboard: 'Loading dashboard…',
    suspensionDuration: 'Suspension duration',
    adminDashboard: 'Admin Dashboard',
    monitorCommunity: 'Monitor community health and review reported content.',
    reportManagement: 'Report Management',
    noOpenReports: 'No open reports.',
    author: 'Author',
    reporter: 'Reporter',
    reason: 'Reason',
    reports: 'Reports',
    created: 'Created',
    approveReport: 'Approve report',
    dismissReport: 'Dismiss report',
    deletePost: 'Delete post',
    suspendUser: 'Suspend user…',
    suspend1Day: 'Suspend 1 day',
    suspend7Days: 'Suspend 7 days',
    suspend30Days: 'Suspend 30 days',
    suspendPermanently: 'Suspend permanently',
    securityActivityLogs: 'Security Activity Logs',
    noSecurityLogs: 'No security activity recorded.',
    moderationActionCompleted: 'Moderation action completed.',
    moderationActionFailed: 'Moderation action failed.',
    loadingTags: 'Loading tags...',
    showingTags: 'Showing {count} tags',
    question: 'question',
    questions: 'questions',
  },
  es: {
    home: 'Inicio',
    questions: 'Preguntas',
    community: 'Comunidad',
    tags: 'Etiquetas',
    users: 'Usuarios',
    jobs: 'Trabajos',
    admin: 'Administrador',
    myProfile: 'Mi perfil',
    logout: 'Cerrar sesión',
    logIn: 'Iniciar sesión',
    signUp: 'Registrarse',
    searchQuestions: 'Buscar preguntas...',
    askQuestion: 'Hacer pregunta',
    allQuestions: 'Todas las preguntas',
    questionsCount: '{count} preguntas',
    newest: 'Más recientes',
    active: 'Activas',
    unanswered: 'Sin responder',
    all: 'Todo',
    noQuestionsFound: 'No se encontraron preguntas',
    loadingQuestions: 'Cargando preguntas...',
    votes: 'Votos',
    answers: 'Respuestas',
    views: 'Vistas',
    navigation: 'Navegación',
    loginTitle: 'Iniciar sesión',
    signupTitle: 'Registrarse',
    email: 'Correo electrónico',
    password: 'Contraseña',
    name: 'Nombre',
    forgotPassword: '¿Olvidaste tu contraseña?',
    oneTimePassword: 'Contraseña de un solo uso',
    enterCode: 'Introduce el código de 6 dígitos',
    verifyOtp: 'Verificar OTP',
    saveProfile: 'Guardar perfil',
    cancel: 'Cancelar',
    editProfile: 'Editar perfil',
    about: 'Acerca de',
    skills: 'Habilidades',
    language: 'Idioma',
    selectLanguage: 'Seleccionar idioma',
    currentPlan: 'Plan actual:',
    questionsPerDay: 'preguntas/día',
    questionTitle: 'Título de la pregunta',
    questionTitlePlaceholder: 'Introduce un título claro y específico',
    questionDescription: 'Descripción de la pregunta',
    questionDescriptionPlaceholder: 'Describe tu pregunta en detalle',
    questionTagsPlaceholder: 'Añade etiquetas separadas por comas',
    questionTagsExample: 'Ejemplo: react, node.js, mongodb',
    submitting: 'Enviando...',
    updateQuestion: 'Actualizar pregunta',
    verifyEmail: 'Verificar correo',
    otpPrompt: 'Introduce el OTP enviado a tu {channel} para continuar.',
    latest: 'Más reciente',
    following: 'Siguiendo',
    saved: 'Guardado',
    search: 'Buscar',
    trendingNow: 'Tendencias ahora',
    shareUpdate: 'Comparte una actualización',
    image: 'Imagen',
    publish: 'Publicar',
    noPostsFound: 'No se encontraron publicaciones',
    communityDescription: 'Proyectos, código, logros de aprendizaje y conversaciones técnicas útiles.',
    searchHashtag: 'Buscar o #hashtag',
    likes: 'me gusta',
    comments: 'comentarios',
    postPlaceholder: 'Comparte un proyecto, logro o pregunta. Usa #hashtags y @menciones.',
    codeSnippetPlaceholder: 'Fragmento de código opcional',
    deletePostConfirmation: '¿Eliminar esta publicación?',
    editPostPrompt: 'Edita tu publicación',
    loadingMorePosts: 'Cargando más publicaciones…',
    scrollToLoadMorePosts: 'Desplázate para cargar más publicaciones…',
    tryAnotherSearch: 'Prueba otra búsqueda o sé el primero en compartir.',
    reply: 'Responder',
    comment: 'Comentar',
    writeReply: 'Escribe una respuesta…',
    writeComment: 'Escribe un comentario…',
    loadingJobs: 'Cargando empleos...',
    jobsAvailable: 'Empleos disponibles',
    noJobsPosted: 'Aún no hay empleos publicados.',
    postJob: 'Publicar un empleo',
    jobTitle: 'Título del empleo',
    company: 'Empresa',
    location: 'Ubicación',
    salary: 'Salario',
    requirements: 'Requisitos',
    followers: 'Seguidores',
    activeSessions: 'Sesiones activas',
    trustDevice: 'Confiar en este dispositivo',
    revokeSession: 'Revocar sesión',
    reputationHistory: 'Historial de reputación',
    transferReputation: 'Transferir reputación',
    joinedOn: 'Se unió el',
    subscriptionBilling: 'Panel de suscripción y facturación',
    activePlan: 'Plan activo',
    renewalDate: 'Fecha de renovación',
    questionLimit: 'Límite de preguntas',
    unlimited: 'Ilimitado',
    upgradeMembership: 'Mejorar membresía',
    upgradeTo: 'Mejorar a',
    paymentHistory: 'Historial de pagos y facturas',
    amount: 'Monto',
    invoice: 'Factura',
    downloadInvoice: 'Descargar factura',
    pending: 'Pendiente',
    overflowBlog: 'Blog de Overflow',
    welcomeToNexStack: 'Bienvenido a NexStack',
    tipsForQuestions: 'Consejos para hacer mejores preguntas de programación',
    learnMern: 'Aprende MERN Stack con proyectos reales',
    featuredOnMeta: 'Destacado en Meta',
    askClearQuestions: 'Haz preguntas claras y detalladas.',
    helpOtherDevelopers: 'Ayuda a otros desarrolladores respondiendo.',
    voteUseful: 'Vota por preguntas y respuestas útiles.',
    hotTags: 'Etiquetas populares',
    communityStats: 'Estadísticas de la comunidad',
    switchLanguage: 'Cambiar idioma',
    languageUpdated: 'Idioma actualizado correctamente.',
    // ✅ ADD THESE:
    "Live Count": "Conteo en vivo",
    "Registered Members": "Miembros registrados",
    "Find answers and share your technical questions": "Encuentra respuestas y comparte tus preguntas técnicas",
    "Browse real developer questions, join discussions, and post your own programming issues.": "Explora preguntas reales de desarrolladores, participa en discusiones y publica tus propios problemas de programación.",
    postAnswer: 'Publicar respuesta',
    backToQuestions: 'Volver a preguntas',
    edit: 'Editar',
    delete: 'Eliminar',
    acceptedAnswer: 'Respuesta aceptada',
    bestAnswer: 'Mejor respuesta',
    acceptAnswer: 'Aceptar respuesta',
    reputation: 'Reputación',
    totalUsers: 'Total de usuarios',
    totalPosts: 'Total de publicaciones',
    totalReports: 'Reportes abiertos',
    activeUsers: 'Usuarios activos (30 días)',
    suspendedUsers: 'Usuarios suspendidos',
    couldNotLoadModeration: 'No se pudo cargar el panel de moderación.',
    suspensionReason: 'Razón de suspensión',
    reportsAgainst: 'Reportes contra esta cuenta',
    communityGuidelineViolation: 'Violación de la guía de la comunidad',
    loadingDashboard: 'Cargando panel…',
    suspensionDuration: 'Duración de la suspensión',
    adminDashboard: 'Panel de administración',
    monitorCommunity: 'Monitorear la salud de la comunidad y revisar contenido reportado.',
    reportManagement: 'Gestión de reportes',
    noOpenReports: 'Sin reportes abiertos.',
    author: 'Autor',
    reporter: 'Reportador',
    reason: 'Razón',
    reports: 'Reportes',
    created: 'Creado',
    approveReport: 'Aprobar reporte',
    dismissReport: 'Descartar reporte',
    deletePost: 'Eliminar publicación',
    suspendUser: 'Suspender usuario…',
    suspend1Day: 'Suspender 1 día',
    suspend7Days: 'Suspender 7 días',
    suspend30Days: 'Suspender 30 días',
    suspendPermanently: 'Suspender permanentemente',
    securityActivityLogs: 'Registros de actividad de seguridad',
    noSecurityLogs: 'Sin actividad de seguridad registrada.',
    moderationActionCompleted: 'Acción de moderación completada.',
    moderationActionFailed: 'Acción de moderación fallida.',
    loadingTags: 'Cargando etiquetas...',
    showingTags: 'Mostrando {count} etiquetas',
    question: 'pregunta',
    questions: 'preguntas',
  },
  hi: {
    home: 'होम',
    questions: 'प्रश्न',
    community: 'समुदाय',
    tags: 'टैग',
    users: 'उपयोगकर्ता',
    jobs: 'नौकरियां',
    admin: 'व्यवस्थापक',
    myProfile: 'मेरा प्रोफ़ाइल',
    logout: 'लॉग आउट',
    logIn: 'लॉग इन',
    signUp: 'साइन अप',
    searchQuestions: 'प्रश्न खोजें...',
    askQuestion: 'प्रश्न पूछें',
    allQuestions: 'सभी प्रश्न',
    questionsCount: '{count} प्रश्न',
    newest: 'नवीनतम',
    active: 'सक्रिय',
    unanswered: 'अनुत्तरित',
    all: 'सभी',
    noQuestionsFound: 'कोई प्रश्न नहीं मिला',
    loadingQuestions: 'प्रश्न लोड हो रहे हैं...',
    votes: 'मत',
    answers: 'उत्तर',
    views: 'दृश्य',
    navigation: 'नेविगेशन',
    loginTitle: 'लॉग इन',
    signupTitle: 'साइन अप',
    email: 'ईमेल',
    password: 'पासवर्ड',
    name: 'नाम',
    forgotPassword: 'पासवर्ड भूल गए?',
    oneTimePassword: 'वन-टाइम पासवर्ड',
    enterCode: '6-अंकीय कोड दर्ज करें',
    verifyOtp: 'OTP सत्यापित करें',
    saveProfile: 'प्रोफ़ाइल सहेजें',
    cancel: 'रद्द करें',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    about: 'के बारे में',
    skills: 'कौशल',
    language: 'भाषा',
    selectLanguage: 'भाषा चुनें',
    currentPlan: 'वर्तमान योजना:',
    questionsPerDay: 'प्रश्न/दिन',
    questionTitle: 'प्रश्न शीर्षक',
    questionTitlePlaceholder: 'एक स्पष्ट, विशिष्ट शीर्षक दर्ज करें',
    questionDescription: 'प्रश्न विवरण',
    questionDescriptionPlaceholder: 'अपने प्रश्न को विस्तार से बताएं',
    questionTagsPlaceholder: 'कॉमा से अलग टैग जोड़ें',
    questionTagsExample: 'उदाहरण: react, node.js, mongodb',
    submitting: 'सबमिट किया जा रहा है...',
    updateQuestion: 'प्रश्न अपडेट करें',
    verifyEmail: 'ईमेल सत्यापित करें',
    otpPrompt: 'जारी रखने के लिए आपके {channel} पर भेजा गया OTP दर्ज करें।',
    latest: 'नवीनतम',
    following: 'पालन कर रहे हैं',
    saved: 'सहेजा गया',
    search: 'खोज',
    trendingNow: 'अब ट्रेंडिंग',
    shareUpdate: 'अपडेट साझा करें',
    image: 'छवि',
    publish: 'प्रकाशित करें',
    noPostsFound: 'कोई पोस्ट नहीं मिली',
    communityDescription: 'प्रोजेक्ट, कोड, सीखने की जीत, और सहायक तकनीकी बातचीत।',
    searchHashtag: 'खोजें या #हैशटैग',
    likes: 'पसंद',
    comments: 'टिप्पणियाँ',
    postPlaceholder: 'एक परियोजना, उपलब्धि, या प्रश्न साझा करें। #हैशटैग और @मेंशन का उपयोग करें।',
    codeSnippetPlaceholder: 'वैकल्पिक कोड स्निपेट',
    deletePostConfirmation: 'क्या आप इस पोस्ट को हटाना चाहते हैं?',
    editPostPrompt: 'अपनी पोस्ट संपादित करें',
    loadingMorePosts: 'अधिक पोस्ट लोड हो रही हैं…',
    scrollToLoadMorePosts: 'अधिक पोस्ट लोड करने के लिए स्क्रॉल करें…',
    tryAnotherSearch: 'एक अन्य खोज आज़माएँ या पहले साझा करें।',
    reply: 'उत्तर दें',
    comment: 'टिप्पणी',
    writeReply: 'एक उत्तर लिखें…',
    writeComment: 'एक टिप्पणी लिखें…',
    loadingJobs: 'नौकरियां लोड हो रही हैं...',
    jobsAvailable: 'उपलब्ध नौकरियां',
    noJobsPosted: 'अभी तक कोई नौकरी पोस्ट नहीं की गई।',
    postJob: 'नौकरी पोस्ट करें',
    jobTitle: 'नौकरी का शीर्षक',
    company: 'कंपनी',
    location: 'स्थान',
    salary: 'वेतन',
    requirements: 'आवश्यकताएँ',
    followers: 'अनुयायी',
    activeSessions: 'सक्रिय सत्र',
    trustDevice: 'इस डिवाइस पर भरोसा करें',
    revokeSession: 'सेशन रद्द करें',
    reputationHistory: 'प्रतिष्ठा इतिहास',
    transferReputation: 'प्रतिष्ठा हस्तांतरित करें',
    joinedOn: 'शामिल हुए',
    subscriptionBilling: 'सदस्यता और बिलिंग डैशबोर्ड',
    activePlan: 'सक्रिय योजना',
    renewalDate: 'नवीनीकरण तिथि',
    questionLimit: 'प्रश्न सीमा',
    unlimited: 'असीमित',
    upgradeMembership: 'सदस्यता उन्नत करें',
    upgradeTo: 'में अपग्रेड करें',
    paymentHistory: 'भुगतान इतिहास और चालान',
    amount: 'राशि',
    invoice: 'चालान',
    downloadInvoice: 'चालान डाउनलोड करें',
    pending: 'लंबित',
    overflowBlog: 'ओवरफ़्लो ब्लॉग',
    welcomeToNexStack: 'NexStack में आपका स्वागत है',
    tipsForQuestions: 'बेहतर प्रोग्रामिंग प्रश्न पूछने के सुझाव',
    learnMern: 'वास्तविक प्रोजेक्ट के माध्यम से MERN स्टैक सीखें',
    featuredOnMeta: 'Meta पर प्रदर्शित',
    askClearQuestions: 'स्पष्ट और विस्तृत प्रश्न पूछें।',
    helpOtherDevelopers: 'उत्तर देकर अन्य डेवलपर्स की मदद करें।',
    voteUseful: 'उपयोगी प्रश्नों और उत्तरों के लिए वोट करें।',
    hotTags: 'लोकप्रिय टैग',
    communityStats: 'समुदाय डेटा',
    switchLanguage: 'भाषा बदलें',
    languageUpdated: 'भाषा सफलतापूर्वक अपडेट की गई।',
    "Live Count": 'लाइव काउंट',
    "Registered Members": 'पंजीकृत सदस्य',
    "Find answers and share your technical questions": 'उत्तर खोजें और अपने तकनीकी प्रश्न साझा करें',
    "Browse real developer questions, join discussions, and post your own programming issues.": 'वास्तविक डेवलपर प्रश्न ब्राउज़ करें, चर्चा में भाग लें, और अपने स्वयं के प्रोग्रामिंग मुद्दे पोस्ट करें।',
    postAnswer: 'उत्तर पोस्ट करें',
    backToQuestions: 'प्रश्नों पर वापस जाएँ',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    acceptedAnswer: 'स्वीकृत उत्तर',
    bestAnswer: 'सर्वश्रेष्ठ उत्तर',
    acceptAnswer: 'उत्तर स्वीकार करें',
    reputation: 'प्रतिष्ठा',
    totalUsers: 'कुल उपयोगकर्ता',
    totalPosts: 'कुल पोस्ट',
    totalReports: 'खुली रिपोर्टें',
    activeUsers: 'सक्रिय उपयोगकर्ता (30 दिन)',
    suspendedUsers: 'निलंबित उपयोगकर्ता',
    couldNotLoadModeration: 'मॉडरेशन डैशबोर्ड नहीं लोड हो सका।',
    suspensionReason: 'निलंबन का कारण',
    reportsAgainst: 'इस खाते के खिलाफ रिपोर्टें',
    communityGuidelineViolation: 'सामुदायिक दिशानिर्देश का उल्लंघन',
    loadingDashboard: 'डैशबोर्ड लोड हो रहा है…',
    suspensionDuration: 'निलंबन की अवधि',
    adminDashboard: 'व्यवस्थापक डैशबोर्ड',
    monitorCommunity: 'सामुदायिक स्वास्थ्य की निगरानी करें और रिपोर्ट की गई सामग्री की समीक्षा करें।',
    reportManagement: 'रिपोर्ट प्रबंधन',
    noOpenReports: 'कोई खुली रिपोर्ट नहीं।',
    author: 'लेखक',
    reporter: 'रिपोर्टर',
    reason: 'कारण',
    reports: 'रिपोर्टें',
    created: 'बनाया गया',
    approveReport: 'रिपोर्ट को मंजूरी दें',
    dismissReport: 'रिपोर्ट को खारिज करें',
    deletePost: 'पोस्ट हटाएं',
    suspendUser: 'उपयोगकर्ता को निलंबित करें…',
    suspend1Day: '1 दिन के लिए निलंबित करें',
    suspend7Days: '7 दिनों के लिए निलंबित करें',
    suspend30Days: '30 दिनों के लिए निलंबित करें',
    suspendPermanently: 'स्थायी रूप से निलंबित करें',
    securityActivityLogs: 'सुरक्षा गतिविधि लॉग',
    noSecurityLogs: 'कोई सुरक्षा गतिविधि दर्ज नहीं।',
    moderationActionCompleted: 'मॉडरेशन कार्रवाई पूरी हुई।',
    moderationActionFailed: 'मॉडरेशन कार्रवाई विफल।',
    loadingTags: 'टैग लोड हो रहे हैं...',
    showingTags: '{count} टैग दिखा रहे हैं',
    question: 'प्रश्न',
    questions: 'प्रश्न',
  },
  pt: {
    home: 'Início',
    questions: 'Perguntas',
    community: 'Comunidade',
    tags: 'Etiquetas',
    users: 'Usuários',
    jobs: 'Vagas',
    admin: 'Admin',
    myProfile: 'Meu Perfil',
    logout: 'Sair',
    logIn: 'Entrar',
    signUp: 'Cadastrar',
    searchQuestions: 'Pesquisar perguntas...',
    askQuestion: 'Fazer pergunta',
    allQuestions: 'Todas as perguntas',
    questionsCount: '{count} perguntas',
    newest: 'Mais recentes',
    active: 'Ativas',
    unanswered: 'Sem resposta',
    all: 'Tudo',
    noQuestionsFound: 'Nenhuma pergunta encontrada',
    loadingQuestions: 'Carregando perguntas...',
    votes: 'Votos',
    answers: 'Respostas',
    views: 'Visualizações',
    navigation: 'Navegação',
    loginTitle: 'Entrar',
    signupTitle: 'Cadastrar',
    email: 'Email',
    password: 'Senha',
    name: 'Nome',
    forgotPassword: 'Esqueceu a senha?',
    oneTimePassword: 'Senha única',
    enterCode: 'Digite o código de 6 dígitos',
    verifyOtp: 'Verificar OTP',
    saveProfile: 'Salvar perfil',
    cancel: 'Cancelar',
    editProfile: 'Editar perfil',
    about: 'Sobre',
    skills: 'Habilidades',
    language: 'Idioma',
    selectLanguage: 'Selecionar idioma',
    currentPlan: 'Plano atual:',
    questionsPerDay: 'perguntas/dia',
    questionTitle: 'Título da pergunta',
    questionTitlePlaceholder: 'Digite um título claro e específico',
    questionDescription: 'Descrição da pergunta',
    questionDescriptionPlaceholder: 'Descreva sua pergunta em detalhes',
    questionTagsPlaceholder: 'Adicione tags separadas por vírgulas',
    questionTagsExample: 'Exemplo: react, node.js, mongodb',
    submitting: 'Enviando...',
    updateQuestion: 'Atualizar pergunta',
    verifyEmail: 'Verificar email',
    otpPrompt: 'Digite o OTP enviado para seu {channel} para continuar.',
    latest: 'Mais recentes',
    following: 'Seguindo',
    saved: 'Salvo',
    search: 'Pesquisar',
    trendingNow: 'Tendências agora',
    shareUpdate: 'Compartilhar atualização',
    image: 'Imagem',
    publish: 'Publicar',
    noPostsFound: 'Nenhuma postagem encontrada',
    communityDescription: 'Projetos, código, conquistas de aprendizado e conversas técnicas úteis.',
    searchHashtag: 'Pesquisar ou #hashtag',
    likes: 'curtidas',
    comments: 'comentários',
    postPlaceholder: 'Compartilhe um projeto, conquista ou pergunta. Use #hashtags e @menções.',
    codeSnippetPlaceholder: 'Trecho de código opcional',
    deletePostConfirmation: 'Excluir esta postagem?',
    editPostPrompt: 'Edite sua postagem',
    loadingMorePosts: 'Carregando mais postagens…',
    scrollToLoadMorePosts: 'Role para carregar mais postagens…',
    tryAnotherSearch: 'Tente outra pesquisa ou seja o primeiro a compartilhar.',
    reply: 'Responder',
    comment: 'Comentar',
    writeReply: 'Escreva uma resposta…',
    writeComment: 'Escreva um comentário…',
    loadingJobs: 'Carregando vagas...',
    jobsAvailable: 'Vagas disponíveis',
    noJobsPosted: 'Nenhuma vaga publicada ainda.',
    postJob: 'Publicar vaga',
    jobTitle: 'Título da vaga',
    company: 'Empresa',
    location: 'Localização',
    salary: 'Salário',
    requirements: 'Requisitos',
    followers: 'Seguidores',
    activeSessions: 'Sessões ativas',
    trustDevice: 'Confiar neste dispositivo',
    revokeSession: 'Revogar sessão',
    reputationHistory: 'Histórico de reputação',
    transferReputation: 'Transferir reputação',
    joinedOn: 'Ingressou em',
    subscriptionBilling: 'Painel de assinatura e cobrança',
    activePlan: 'Plano ativo',
    renewalDate: 'Data de renovação',
    questionLimit: 'Limite de perguntas',
    unlimited: 'Ilimitado',
    upgradeMembership: 'Atualizar assinatura',
    upgradeTo: 'Atualizar para',
    paymentHistory: 'Histórico de pagamentos e faturas',
    amount: 'Valor',
    invoice: 'Fatura',
    downloadInvoice: 'Baixar fatura',
    pending: 'Pendente',
    overflowBlog: 'Blog do Overflow',
    welcomeToNexStack: 'Bem-vindo ao NexStack',
    tipsForQuestions: 'Dicas para fazer perguntas de programação melhores',
    learnMern: 'Aprenda MERN Stack com projetos reais',
    featuredOnMeta: 'Destaque no Meta',
    askClearQuestions: 'Faça perguntas claras e detalhadas.',
    helpOtherDevelopers: 'Ajude outros desenvolvedores respondendo.',
    voteUseful: 'Vote em perguntas e respostas úteis.',
    hotTags: 'Tópicos populares',
    communityStats: 'Estatísticas da comunidade',
    switchLanguage: 'Mudar idioma',
    languageUpdated: 'Idioma atualizado com sucesso.',
    "Live Count": 'Contagem ao vivo',
    "Registered Members": 'Membros registrados',
    "Find answers and share your technical questions": 'Encontre respostas e compartilhe suas perguntas técnicas',
    "Browse real developer questions, join discussions, and post your own programming issues.": 'Navegue por perguntas reais de desenvolvedores, participe de discussões e publique seus próprios problemas de programação.',
    postAnswer: 'Postar resposta',
    backToQuestions: 'Voltar para perguntas',
    edit: 'Editar',
    delete: 'Excluir',
    acceptedAnswer: 'Resposta aceita',
    bestAnswer: 'Melhor resposta',
    acceptAnswer: 'Aceitar resposta',
    reputation: 'Reputação',
    totalUsers: 'Total de usuários',
    totalPosts: 'Total de postagens',
    totalReports: 'Denúncias abertas',
    activeUsers: 'Usuários ativos (30 dias)',
    suspendedUsers: 'Usuários suspensos',
    couldNotLoadModeration: 'Não foi possível carregar o painel de moderação.',
    suspensionReason: 'Motivo da suspensão',
    reportsAgainst: 'Denúncias contra esta conta',
    communityGuidelineViolation: 'Violação das diretrizes da comunidade',
    loadingDashboard: 'Carregando painel…',
    suspensionDuration: 'Duração da suspensão',
    adminDashboard: 'Painel de administração',
    monitorCommunity: 'Monitore a saúde da comunidade e analise o conteúdo denunciado.',
    reportManagement: 'Gerenciamento de denúncias',
    noOpenReports: 'Nenhuma denúncia aberta.',
    author: 'Autor',
    reporter: 'Denunciante',
    reason: 'Motivo',
    reports: 'Denúncias',
    created: 'Criado',
    approveReport: 'Aprovar denúncia',
    dismissReport: 'Descartar denúncia',
    deletePost: 'Deletar postagem',
    suspendUser: 'Suspender usuário…',
    suspend1Day: 'Suspender 1 dia',
    suspend7Days: 'Suspender 7 dias',
    suspend30Days: 'Suspender 30 dias',
    suspendPermanently: 'Suspender permanentemente',
    securityActivityLogs: 'Registros de atividade de segurança',
    noSecurityLogs: 'Nenhuma atividade de segurança registrada.',
    moderationActionCompleted: 'Ação de moderação concluída.',
    moderationActionFailed: 'Ação de moderação falhou.',
    loadingTags: 'Carregando tags...',
    showingTags: 'Mostrando {count} tags',
    question: 'pergunta',
    questions: 'perguntas',
  },
  zh: {
    home: '首页',
    questions: '问题',
    community: '社区',
    tags: '标签',
    users: '用户',
    jobs: '职位',
    admin: '管理',
    myProfile: '我的个人资料',
    logout: '注销',
    logIn: '登录',
    signUp: '注册',
    searchQuestions: '搜索问题...',
    askQuestion: '提问',
    allQuestions: '所有问题',
    questionsCount: '{count} 个问题',
    newest: '最新',
    active: '活跃',
    unanswered: '未回答',
    all: '全部',
    noQuestionsFound: '未找到问题',
    loadingQuestions: '正在加载问题...',
    votes: '票数',
    answers: '回答',
    views: '浏览',
    navigation: '导航',
    loginTitle: '登录',
    signupTitle: '注册',
    email: '电子邮件',
    password: '密码',
    name: '姓名',
    forgotPassword: '忘记密码？',
    oneTimePassword: '一次性密码',
    enterCode: '输入 6 位代码',
    verifyOtp: '验证 OTP',
    saveProfile: '保存资料',
    cancel: '取消',
    editProfile: '编辑资料',
    about: '关于',
    skills: '技能',
    language: '语言',
    selectLanguage: '选择语言',
    currentPlan: '当前计划：',
    questionsPerDay: '问题/天',
    questionTitle: '问题标题',
    questionTitlePlaceholder: '输入一个清晰、具体的标题',
    questionDescription: '问题描述',
    questionDescriptionPlaceholder: '详细描述您的问题',
    questionTagsPlaceholder: '添加以逗号分隔的标签',
    questionTagsExample: '示例：react, node.js, mongodb',
    submitting: '正在提交...',
    updateQuestion: '更新问题',
    verifyEmail: '验证电子邮件',
    otpPrompt: '输入发送到您的 {channel} 的 OTP 继续。',
    latest: '最新',
    following: '关注',
    saved: '已保存',
    search: '搜索',
    trendingNow: '当前趋势',
    shareUpdate: '分享更新',
    image: '图片',
    publish: '发布',
    noPostsFound: '未找到帖子',
    communityDescription: '项目、代码、学习成果和有帮助的技术讨论。',
    searchHashtag: '搜索或 #标签',
    likes: '喜欢',
    comments: '评论',
    postPlaceholder: '分享项目、成就或问题。使用 #标签 和 @提及。',
    codeSnippetPlaceholder: '可选代码片段',
    deletePostConfirmation: '删除这条帖子？',
    editPostPrompt: '编辑您的帖子',
    loadingMorePosts: '正在加载更多帖子…',
    scrollToLoadMorePosts: '滚动以加载更多帖子…',
    tryAnotherSearch: '尝试另一个搜索或成为第一个分享的人。',
    reply: '回复',
    comment: '评论',
    writeReply: '写回复…',
    writeComment: '写评论…',
    loadingJobs: '正在加载职位...',
    jobsAvailable: '可用职位',
    noJobsPosted: '尚未发布职位。',
    postJob: '发布职位',
    jobTitle: '职位标题',
    company: '公司',
    location: '地点',
    salary: '薪水',
    requirements: '要求',
    followers: '关注者',
    activeSessions: '活动会话',
    trustDevice: '信任此设备',
    revokeSession: '撤销会话',
    reputationHistory: '声誉历史',
    transferReputation: '转移声誉',
    joinedOn: '加入于',
    subscriptionBilling: '订阅和计费仪表板',
    activePlan: '活动计划',
    renewalDate: '续订日期',
    questionLimit: '问题限制',
    unlimited: '无限',
    upgradeMembership: '升级会员资格',
    upgradeTo: '升级到',
    paymentHistory: '付款历史和发票',
    amount: '金额',
    invoice: '发票',
    downloadInvoice: '下载发票',
    pending: '待处理',
    overflowBlog: 'Overflow 博客',
    welcomeToNexStack: '欢迎来到 NexStack',
    tipsForQuestions: '提问更好的编程问题的技巧',
    learnMern: '通过真实项目学习 MERN 堆栈',
    featuredOnMeta: 'Meta 精选',
    askClearQuestions: '提出清晰详细的问题。',
    helpOtherDevelopers: '通过回答帮助其他开发者。',
    voteUseful: '为有用的问题和答案投票。',
    hotTags: '热门标签',
    communityStats: '社区统计',
    switchLanguage: '切换语言',
    languageUpdated: '语言已成功更新。',
    "Live Count": '实时计数',
    "Registered Members": '注册会员',
    "Find answers and share your technical questions": '查找答案并分享您的技术问题',
    "Browse real developer questions, join discussions, and post your own programming issues.": '浏览真实的开发者问题，加入讨论并发布您自己的编程问题。',
    postAnswer: '发布回答',
    backToQuestions: '返回问题',
    edit: '编辑',
    delete: '删除',
    acceptedAnswer: '被采纳的答案',
    bestAnswer: '最佳答案',
    acceptAnswer: '接受答案',
    reputation: '声誉',
    totalUsers: '总用户数',
    totalPosts: '总发帖数',
    totalReports: '未解决的报告',
    activeUsers: '活跃用户 (30 天)',
    suspendedUsers: '暂停的用户',
    couldNotLoadModeration: '无法加载审核仪表板。',
    suspensionReason: '暂停原因',
    reportsAgainst: '针对此帐户的报告',
    communityGuidelineViolation: '违反社区指南',
    loadingDashboard: '正在加载仪表板…',
    suspensionDuration: '暂停时间',
    adminDashboard: '管理员仪表板',
    monitorCommunity: '监控社区健康状况并审查举报的内容。',
    reportManagement: '报告管理',
    noOpenReports: '没有未解决的报告。',
    author: '作者',
    reporter: '举报者',
    reason: '原因',
    reports: '报告',
    created: '创建',
    approveReport: '批准报告',
    dismissReport: '驳回报告',
    deletePost: '删除帖子',
    suspendUser: '暂停用户…',
    suspend1Day: '暂停 1 天',
    suspend7Days: '暂停 7 天',
    suspend30Days: '暂停 30 天',
    suspendPermanently: '永久暂停',
    securityActivityLogs: '安全活动日志',
    noSecurityLogs: '没有记录的安全活动。',
    moderationActionCompleted: '审核操作已完成。',
    moderationActionFailed: '审核操作失败。',
    loadingTags: '正在加载标签...',
    showingTags: '显示 {count} 个标签',
    question: '问题',
    questions: '问题',
  },
  fr: {
    home: 'Accueil',
    questions: 'Questions',
    community: 'Communauté',
    tags: 'Étiquettes',
    users: 'Utilisateurs',
    jobs: 'Emplois',
    admin: 'Admin',
    myProfile: 'Mon profil',
    logout: 'Déconnexion',
    logIn: 'Connexion',
    signUp: 'S\'inscrire',
    searchQuestions: 'Rechercher des questions...',
    askQuestion: 'Poser une question',
    allQuestions: 'Toutes les questions',
    questionsCount: '{count} questions',
    newest: 'Les plus récentes',
    active: 'Actives',
    unanswered: 'Sans réponse',
    all: 'Tout',
    noQuestionsFound: 'Aucune question trouvée',
    loadingQuestions: 'Chargement des questions...',
    votes: 'Votes',
    answers: 'Réponses',
    views: 'Vues',
    navigation: 'Navigation',
    loginTitle: 'Connexion',
    signupTitle: 'S\'inscrire',
    email: 'Email',
    password: 'Mot de passe',
    name: 'Nom',
    forgotPassword: 'Mot de passe oublié ?',
    oneTimePassword: 'Mot de passe à usage unique',
    enterCode: 'Entrez le code à 6 chiffres',
    verifyOtp: 'Vérifier OTP',
    saveProfile: 'Enregistrer le profil',
    cancel: 'Annuler',
    editProfile: 'Modifier le profil',
    about: 'À propos',
    skills: 'Compétences',
    language: 'Langue',
    selectLanguage: 'Sélectionner la langue',
    verifyEmail: 'Vérifier l\'email',
    otpPrompt: 'Entrez l\'OTP envoyé à votre {channel} pour continuer.',
    latest: 'Dernier',
    following: 'Suit',
    saved: 'Enregistré',
    search: 'Recherche',
    trendingNow: 'Tendances maintenant',
    shareUpdate: 'Partager une mise à jour',
    image: 'Image',
    publish: 'Publier',
    noPostsFound: 'Aucun post trouvé',
    communityDescription: 'Projets, code, réussites d\'apprentissage et conversations techniques utiles.',
    searchHashtag: 'Recherche ou #hashtag',
    likes: 'j\'aime',
    comments: 'commentaires',
    postPlaceholder: 'Partagez un projet, une réussite ou une question. Utilisez #hashtags et @mentions.',
    codeSnippetPlaceholder: 'Extrait de code facultatif',
    deletePostConfirmation: 'Supprimer cette publication ?',
    editPostPrompt: 'Modifiez votre publication',
    loadingMorePosts: 'Chargement de plus de publications…',
    scrollToLoadMorePosts: 'Faites défiler pour charger plus de publications…',
    tryAnotherSearch: 'Essayez une autre recherche ou soyez le premier à partager.',
    reply: 'Répondre',
    comment: 'Commentaire',
    writeReply: 'Écrire une réponse…',
    writeComment: 'Écrire un commentaire…',
    loadingJobs: 'Chargement des emplois...',
    jobsAvailable: 'Emplois disponibles',
    noJobsPosted: 'Aucun emploi publié pour le moment.',
    postJob: 'Publier une offre',
    jobTitle: 'Titre du poste',
    company: 'Entreprise',
    location: 'Lieu',
    salary: 'Salaire',
    requirements: 'Exigences',
    followers: 'Abonnés',
    activeSessions: 'Sessions actives',
    trustDevice: 'Faire confiance à cet appareil',
    revokeSession: 'Révoquer la session',
    reputationHistory: 'Historique de réputation',
    transferReputation: 'Transférer la réputation',
    joinedOn: 'A rejoint le',
    subscriptionBilling: 'Tableau de bord d\'abonnement et de facturation',
    activePlan: 'Plan actif',
    renewalDate: 'Date de renouvellement',
    questionLimit: 'Limite de questions',
    unlimited: 'Illimité',
    upgradeMembership: 'Améliorer l\'abonnement',
    upgradeTo: 'Mettre à niveau vers',
    paymentHistory: 'Historique des paiements et factures',
    amount: 'Montant',
    invoice: 'Facture',
    downloadInvoice: 'Télécharger la facture',
    pending: 'En attente',
    overflowBlog: 'Blog Overflow',
    welcomeToNexStack: 'Bienvenue sur NexStack',
    tipsForQuestions: 'Conseils pour poser de meilleures questions de programmation',
    learnMern: 'Apprenez MERN Stack à travers des projets réels',
    featuredOnMeta: 'En vedette sur Meta',
    askClearQuestions: 'Posez des questions claires et détaillées.',
    helpOtherDevelopers: 'Aidez d\'autres développeurs en répondant.',
    voteUseful: 'Votez pour les questions et réponses utiles.',
    hotTags: 'Tags populaires',
    communityStats: 'Statistiques de la communauté',
    switchLanguage: 'Changer de langue',
    languageUpdated: 'Langue mise à jour avec succès.',
    "Live Count": 'Nombre en direct',
    "Registered Members": 'Membres enregistrés',
    "Find answers and share your technical questions": 'Trouvez des réponses et partagez vos questions techniques',
    "Browse real developer questions, join discussions, and post your own programming issues.": 'Parcourez de vraies questions de développeurs, participez à des discussions et publiez vos propres problèmes de programmation.',
    postAnswer: 'Publier une réponse',
    backToQuestions: 'Retour aux questions',
    edit: 'Modifier',
    delete: 'Supprimer',
    acceptedAnswer: 'Réponse acceptée',
    bestAnswer: 'Meilleure réponse',
    acceptAnswer: 'Accepter la réponse',
    reputation: 'Réputation',
    totalUsers: 'Nombre total d\'utilisateurs',
    totalPosts: 'Nombre total de publications',
    totalReports: 'Rapports ouverts',
    activeUsers: 'Utilisateurs actifs (30 jours)',
    suspendedUsers: 'Utilisateurs suspendus',
    couldNotLoadModeration: 'Impossible de charger le tableau de bord de modération.',
    suspensionReason: 'Motif de la suspension',
    reportsAgainst: 'Rapports contre ce compte',
    communityGuidelineViolation: 'Violation des directives communautaires',
    loadingDashboard: 'Chargement du tableau de bord…',
    suspensionDuration: 'Durée de la suspension',
    adminDashboard: 'Tableau de bord d\'administration',
    monitorCommunity: 'Surveillez la santé de la communauté et révisez le contenu signalé.',
    reportManagement: 'Gestion des rapports',
    noOpenReports: 'Aucun rapport ouvert.',
    author: 'Auteur',
    reporter: 'Personne ayant signalé',
    reason: 'Raison',
    reports: 'Rapports',
    created: 'Créé',
    approveReport: 'Approuver le rapport',
    dismissReport: 'Rejeter le rapport',
    deletePost: 'Supprimer la publication',
    suspendUser: 'Suspendre l\'utilisateur…',
    suspend1Day: 'Suspendre 1 jour',
    suspend7Days: 'Suspendre 7 jours',
    suspend30Days: 'Suspendre 30 jours',
    suspendPermanently: 'Suspendre définitivement',
    securityActivityLogs: 'Journaux d\'activité de sécurité',
    noSecurityLogs: 'Aucune activité de sécurité enregistrée.',
    moderationActionCompleted: 'Action de modération terminée.',
    moderationActionFailed: 'Échec de l\'action de modération.',
    loadingTags: 'Chargement des tags...',
    showingTags: 'Affichage de {count} tags',
    question: 'question',
    questions: 'questions',
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => localStorage.getItem('language') || 'en');
  const [pendingLanguage, setPendingLanguage] = useState(null);
  const [verificationMessage, setVerificationMessage] = useState('');
  const [otpCode, setOtpCode] = useState('');

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (value) => {
    setLanguageState(value);
    setVerificationMessage('');
  };

  const setOtp = (value) => setOtpCode(value);

  const changeLanguage = async (nextLanguage, user) => {
    if (!user) {
      setLanguage(nextLanguage);
      return { success: true };
    }

    try {
      // ✅ Direct language update - NO OTP verification
      const response = await API.patch('/users/language/update', { 
        language: nextLanguage 
      });
      
      setLanguage(nextLanguage);
      setVerificationMessage('');
      
      // Update user in localStorage
      if (user) {
        localStorage.setItem('user', JSON.stringify({ ...user, language: nextLanguage }));
      }
      
      return { success: true, ...response.data };
    } catch (error) {
      console.error("Language change error:", error);
      throw error;
    }
  };

  const confirmLanguageChange = async (otpCode) => {
    if (!pendingLanguage) {
      throw new Error('No pending language change.');
    }

    try {
      const response = await API.post('/users/language/confirm', {
        language: pendingLanguage.language,
        otpCode,
      });
      setLanguage(pendingLanguage.language);
      setPendingLanguage(null);
      setVerificationMessage('');
      const user = JSON.parse(localStorage.getItem('user') || 'null');
      if (user) {
        localStorage.setItem('user', JSON.stringify({ ...user, language: pendingLanguage.language }));
      }
      return { success: true, ...response.data };
    } catch (error) {
      throw error;
    }
  };

  const t = (key, fallback = '') => {
    const dictionary = translations[language] || translations.en;
    const value = dictionary[key];
    return value || translations.en[key] || fallback;
  };

  const supportedLanguages = [
    { code: 'en', label: 'English' },
    { code: 'es', label: 'Español' },
    { code: 'hi', label: 'हिंदी' },
    { code: 'pt', label: 'Português' },
    { code: 'zh', label: '中文' },
    { code: 'fr', label: 'Français' },
  ];

  const value = useMemo(() => ({
    language,
    setLanguage,
    supportedLanguages,
    t,
    changeLanguage,
    confirmLanguageChange,
    pendingLanguage,
    verificationMessage,
    otpCode,
    setOtp,
  }), [language, pendingLanguage, verificationMessage, otpCode]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}